### ISSUE TITLE
[RFC] New Augmentation techniques in Torchvison

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#3817]
## 🚀 Feature

Inclusion of new Augmentation techniques in `torchvision.transforms`. 

## Motivation

Transforms are important for data augmentation :sweat_smile: 

## Proposals

- [x] [RandAugment](https://arxiv.org/abs/1909.13719v2) Citations 306 #4348
- [x] ~~[Cutout](https://arxiv.org/abs/1708.04552) Citations 964~~ Superseded by [RandomErasing](https://pytorch.org/vision/stable/transforms.html#torchvision.transforms.RandomErasing)
- [x] [MixUp](https://arxiv.org/abs/1710.09412) Citations 1624 [Code](https://github.com/facebookresearch/mixup-cifar10) (Note it is CC-BY-NC-license) #4379
- [x] [CutMix](https://arxiv.org/abs/1905.04899) Citations 437 [Code](https://github.com/clovaai/CutMix-PyTorch)  ICCV 2019 #4379 
- [ ] [AugMix](https://github.com/google-research/augmix) Citations 157
- [ ] [FastAutoAugment](https://arxiv.org/abs/1905.00397) Citations 135 NeurIPS 2019 [Code](https://github.com/kakaobrain/fast-autoaugment) (1k+ GitHub stars)
- [ ] [ReMixMatch](https://arxiv.org/abs/1911.09785) Citations 165
- [ ] [FixMatch](https://arxiv.org/abs/2001.07685) Citations 258
- [ ] [Scale-Jitter](https://arxiv.org/pdf/2012.07177.pdf) Citations 11
- [ ] Port [SSD & SSDlite Augmentations](https://github.com/pytorch/vision/blob/730c5e1eab130e2900c8e839ea08fa11f024516f/references/detection/transforms.py#L30-L239) from references to vision
- [ ] Transforms for color spaces augmentations E.g. rgb2hsv, rgb2bgr, rgb2lab, etc #4029
- [ ] Detection Transforms #1406 #2213 #3980 
- [x] [TrivialAugment](https://arxiv.org/abs/2103.10158) ICCV 2021 #4221 

## Additional context

To visitors
Kindly give a  :+1:  if you think any of these would help in your work. 

Also if you have any transform in mind please provide few details here!

Linked to #3221 

cc @vfdev-5 @fmassa

**Comment by hassiahk** [comment]
Would be nice to have these Augmentations in ``torchvision.transforms``. 😄

Also found this official [code](https://github.com/uoguelph-mlrg/Cutout/blob/master/util/cutout.py) implementation for ``Cutout``.

**Comment by datumbox** [comment]
@oke-aditya Do we need the cutout given we have Random Erasing which can be configured to have the same more or less effect?

**Comment by oke-aditya** [comment]
I think the same. I compared both the implementations. RandomErasing is newer than Cutout, also both the augmentations produce almost similar results.

Also, As per [docs](https://pytorch.org/vision/stable/transforms.html#transforms-on-torch-tensor-only) RandomErasing does not work for for PIL Images. It works only for `torch.Tensor`. I am not sure if that is intentional or needs some work.

**Comment by tflahaul** [comment]
Not a transform idea but what about adding an optional 'target_transforms' argument in `transforms.RandomApply`? That way random imgs transforms and their targets equivalents could be applied at the same time.
The current way of doing so (from what I know) is by writing your own class and using functional transforms. For example :

```py
class AugmentExample:
    def __init__(self, p=0.1):
        self.p = p

    def __call__(self, img, box):
        if self.p < torch.rand(1):
            img = img.flip(-1)
            box = box_hflip(box)
        return img, box
```

Also having a lot more keypoints/bbox transforms would be really great (ideally any image transform that involves a transformation of the targets should be accompanied by one?).

(Sorry if my english isn't right, I speak baguette.)

**Comment by oke-aditya** [comment]
@datumbox is closing this issue intended?

As I understand there is dataset and transforms rework. Which would be a major refactor

Do we plan to migrate all transforms to new ones in near future?

(I had a minor look at the proposal which looks fantastic)

**Comment by datumbox** [comment]
Not at all intended; Github just closed it when I merged the PR. We are certainly not done here :D

**Comment by datumbox** [comment]
@lezwon Thanks a lot for offering to help!

ReMixMatch focuses on learning augmentations and on using unlabelled data. One challenge with that is that the majority of the changes will have to land on references which are outside of TorchVision. Currently the reference scripts are in need of some rework to reduce the amount of duplicate code and improve the overall quality. It's on the top of our todos and until that's done, ideally we would like to avoid introducing significantly complex techniques like ReMixMatch.

I wonder if you would be interested in implementing the AutoAugment Detection algorithm listed above. @vfdev-5 has already added most of the necessary low-level kernels for doing transforms on the BBoxes in `torchvision.prototype`, so what's needed is to implement the AutoAugment technique itself. Of course since it touches prototype APIs it can be tricky too. Let me know your thoughts and perhaps Victor can also pitch in to see if it makes sense to work together and test the new API. Alternatively we can discuss for another contribution that you find interesting.

BTW I'm currently working on the SimpleCopyPaste contribution trying to if we can train more accurate models using it. I'll let you know when I have the full results. :)

**Comment by lezwon** [comment]
@datumbox AutoAugment sounds good. I'll start looking into it. :) Also, I noticed your comment on SimpleCopyPaste PR. Lemme know if I can help in any way :)

**Comment by datumbox** [comment]
@lezwon Fantastic! Just note that I'm talking about this version designed for detection: [AutoAugment Detection](https://arxiv.org/pdf/1906.11172.pdf). This is different from the already supported algorithm for classification. :)

**Comment by vfdev-5** [comment]
Without talking about transforms implementation in the prototype (how input type dispatch would happen etc), the only thing I think we could miss to implement AA Detection is `bbox_only_*` color aug. I do not think that it is something complicated to implement.

**Comment by ain-soph** [comment]
May I ask what's the current plan for the Fast AutoAugment?

I have the implementation of another paper called [Faster Autoaugment](https://arxiv.org/abs/1911.06987):  
https://github.com/ain-soph/trojanzoo/tree/main/trojanvision/utils/autoaugment. 
It's the reimplementation based on [autoalbument](https://github.com/albumentations-team/autoalbument).

Are maintainers interested in embedding this technique as well? If interested, what's the expected api to use it?  
If there is a similar plan for the Fast AutoAugment as the template, I'm glad to follow.
