### ISSUE TITLE
Speed up unit-tests

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3935]
Ticket to keep track of the unit-test speed improvements:
- [x] Detection models #3929: (4.5mins CPU, 0.5mins GPU)
- [x] DeformConv #3933 (1.5mins CPU, 3mins GPU)
- [x] Transformations #3936 (0.75mins CPU, 1.25mins GPU)

Total improvement: 6.75 minutes on CPU and 4.75 on GPU

**Comment by fmassa** [comment]
Thanks a lot for the speedups @datumbox ! That is awesome!
