### ISSUE TITLE
Port more tests files to pytest

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#4033]
Now that we support `pytest`, we want to remove the use of the `unittest` module for different test files. We've already ported a lot of tests in previous issues (https://github.com/pytorch/vision/issues/3987, https://github.com/pytorch/vision/issues/3945, https://github.com/pytorch/vision/issues/3956, https://github.com/pytorch/vision/issues/3951), and we want to extend this to more files now.

### Instructions

I listed the list of files that need to be ported below. If you're interested in working on this issue, please comment below with "I'm working on `file X`" so that others don't pick the same file as you do. To keep things simple, please only submit one PR per file, and don't pick more than 2 files at once. You can pick more files once your PRs are merged. Before picking a group, make sure it wasn't picked by another contributor first.

**Please don't hesitate to ask for guidance and help!** Thanks!!

### How to port a test to pytest

Porting a test from `unittest` to pytest is usually fairly straightforward. For a typical example, see https://github.com/pytorch/vision/pull/3907/files:

- take the test methods out of the  `Tester(unittest.TestCase)` class and just declare it as a function. Note: for some files, it might make sense to keep the class structure, and just rename the class as e.g  `TestBlahBlah:`
- Replace `@unittest.skipIf` with `pytest.mark.skipif(cond, reason=...)`
- remove any use of `self.assertXYZ`.
  - Typically `assertEqual(a, b)` can be replaced by `assert a == b` when a and b are pure python objects (scalars, tuples, lists), and otherwise we can rely on `assert_equal` or `torch.testing.assert_close` (look for other usage of these files in the codebase if needed)
  - `self.assertRaises` should be replaced with the `pytest.raises(Exp, match=...):` context manager, as done in https://github.com/pytorch/vision/pull/3907/files. Same for warnings with `pytest.warns`
  - `self.assertTrue` should be replaced with a plain `assert`
- **When a function uses for loops to tests multiple parameter values**, one should use`pytest.mark.parametrize` instead, as done e.g. in https://github.com/pytorch/vision/pull/3907/files.
- It may make sense to keep related tests within a single class. Not all groups need a dedicated class though, it's on a case-by-case basis.

----

Files that need to be ported:

- [X] `test_datasets_video_utils.py` #4035
  This one will be quite easy, you'll just need to rename the
  Tester(unittest.TestCase) class into e.g. TestVideo, and change `
  with self.assertWarns(UserWarning):` into `with pytest.warns(UserWarning):`
- [x] `test_hub.py` #4038
- [x] `test_datasets_samplers.py` https://github.com/pytorch/vision/pull/4037
- [X] `test_models_detection_anchor_utils.py` #4046
- [X] `test_models_detection_negative_samples.py` #4045
- [x] `test_models_detection_utils.py` https://github.com/pytorch/vision/pull/4036
- [X] `test_onnx.py` #4047
- [X] `test_transforms_video.py` #4040

cc @pmeier

**Comment by AnirudhDagar** [comment]
I'm working on `test_datasets_video_utils.py` and `test_hub.py`.

**Comment by DevPranjal** [comment]
Hey @NicolasHug, I will try working on `test_transforms_video.py`.

**Comment by vivekkumar7089** [comment]
Hi @NicolasHug !! I will work on `test_datasets_samplers.py` and `test_models_detection_anchor_utils.py`.

**Comment by zhiqwang** [comment]
Hey @NicolasHug, I will try working on `test_onnx.py ` and `test_models_detection_negative_samples.py`.

**Comment by AnirudhDagar** [comment]
I'll also pickup the only one left `test_models_detection_utils.py`. Should be quite easy too.

**Comment by NicolasHug** [comment]
All done! Thank you so much everyone for the blazing fast PRs!!
