### ISSUE TITLE
TorchVision Roadmap - 2021 H2

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#4187]
This issue is be used to keep track of the roadmap of TorchVision for the second half of 2021 and get feedback from our users.

For the 2021 H1 roadmap, please see  #3221

- Batteries included:
  - Scope is at https://github.com/pytorch/vision/issues/3911
- Datasets:
  - [x] New datasets design supporting `DataPipes`
- Video
  - [x] Video GPU Decoding (https://github.com/pytorch/vision/issues/2439)
  - [x] Optical Flow support: [RAFT](https://github.com/princeton-vl/RAFT) implementation with datasets and training /evaluation reference and pre-trained weights https://github.com/pytorch/vision/issues/4644
  - [ ] New Video datasets e.g. Charades / SSV2 / EpicKitchen (pending discussion)
- IO:
  - [ ] Faster image decoding. Possible tracks: A100 support (https://github.com/pytorch/vision/issues/3848), Batch-decoding support, better libjpeg-turbo integration
- Perf:
  - [ ] Support for [SIMD instructions for ops](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/README.md)
- Docs:
  - [x] More [gallery examples](https://pytorch.org/vision/stable/auto_examples/index.html) (finish porting the [examples folder](https://github.com/pytorch/vision/tree/master/examples/python))
  - [ ] Possibly move the vision [tutorials](https://pytorch.org/tutorials/) in the torchvision gallery
- Items moved from 2021 H1:
  - [ ] Rotated Boxes (#2761)

**Comment by oke-aditya** [comment]
Guess we should now look at 2022 H1 ? :smiley:  cc @datumbox @NicolasHug

**Comment by datumbox** [comment]
@oke-aditya Thanks for the ping. Yes, we need to finalize and draft a roadmap proposal for 2022H1. We'll do it soon.
