### ISSUE TITLE
New classification datasets support for FLAVA

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5108]
To support our colleagues' work on the [FLAVA](https://arxiv.org/abs/2112.04482) paper, and to foster collaborations in the multi-modal space, we would like to implement a few new datasets. Almost all of them are classification datasets but some also support other tasks like segmentation.

- [x] [Food 101](https://data.vision.ee.ethz.ch/cvl/datasets_extra/food-101/) @jdsgomes #5119
- [x] [Stanford Cars](http://ai.stanford.edu/~jkrause/cars/car_dataset.html) @abhi-glitchhg #5166
- [x] [FGVC Aircraft](https://www.robots.ox.ac.uk/~vgg/data/fgvc-aircraft/) @sallysyw #5178
- [x] [DTD](https://www.robots.ox.ac.uk/~vgg/data/dtd/). A good starting point is [this PR](https://github.com/pytorch/vision/pull/743) from @pmeier #5115 
- [x] [Oxford Pets](https://www.robots.ox.ac.uk/~vgg/data/pets/). This one also comes with ROIs and segmentation masks, which would be nice to support. We could do something similar to [CelebA](https://github.com/pytorch/vision/blob/main/torchvision/datasets/celeba.py) with a `target_type` parameter. @pmeier #5116 
- [x] [Flowers-102](https://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html). @zhiqwang #5177 
- [x] [EuroSAT](https://github.com/phelber/eurosat) @frgfm #5114
- [x] [GSTRB](https://paperswithcode.com/dataset/gtsrb). The homepage is timing out for me, but download links can be found [here](https://github.com/facebookresearch/vissl/blob/484cdecd1a71cb457d8ea74942603b907a23d39d/extra_scripts/datasets/create_gtsrb_data_files.py#L43-L53) @sumukhaithal6 #5117
- [X] [PCAM](https://github.com/basveeling/pcam) @NicolasHug https://github.com/pytorch/vision/pull/5203
- [x] [Clevr Counts](https://cs.stanford.edu/people/jcjohns/clevr/). See also [here](https://github.com/facebookresearch/vissl/blob/484cdecd1a71cb457d8ea74942603b907a23d39d/extra_scripts/datasets/create_clevr_count_data_files.py#L53-L54) for what we exactly need @pmeier #5130
- [x] [FER2013](https://paperswithcode.com/dataset/fer2013) This is a Kaggle dataset, so I'm not sure we'll be able to support download ~(but maybe)~ @pmeier #5120
- [x] [Sun397](https://vision.princeton.edu/projects/2010/SUN/) @saswatpp #5132
- [x] [Country211](https://paperswithcode.com/dataset/country211). Apparently download link is [here](https://github.com/openai/CLIP/blob/main/data/country211.md) @puhuk #5138
- [x] [Rendered SST2](https://github.com/openai/CLIP/commit/efe8cbbdf3e594999706558de021de55e04cab5f) @jdsgomes  #5220

CC-ing @pmeier and @jdsgomes as previously discussed. We're on a **fairly short timeline** for this work, and ideally we would get all these in by **end of January 2022.**
I'm also wondering whether this is something that our open source contributors  @oke-aditya @frgfm @zhiqwang   could be interested in 🚀 ?

### Implementing a new dataset

Implementing a dataset consists of 2 main things:

- The dataset class with a `root`, `split`, `transform` and `target_transform` parameter. When available we should also support a `download` parameter (from what I checked, most of these are download-able apart maybe FER2013). See e.g. the [MNIST](https://github.com/pytorch/vision/blob/eac3dc7bab436725b0ba65e556d3a6ffd43c24e1/torchvision/datasets/mnist.py#L19:L19) class
- A test class which will generate automatic tests, e.g. [this one for MNIST](https://github.com/pytorch/vision/blob/eac3dc7bab436725b0ba65e556d3a6ffd43c24e1/test/test_datasets.py#L1393:L1393).

If there's some ambiguity in the choices to make, the reference to follow is the [VISSL](https://github.com/facebookresearch/vissl/tree/main/extra_scripts/datasets) where most of these datasets are already supported. 

### For contritbutors

If you're interesting in taking one of the datasets above, please comment below with "I'm working on dataset X" so that others don't pick the same! :)

cc @pmeier

**Comment by pmeier** [comment]
I'm going to take DTD and Oxford Pets.

> FER2013 This is a Kaggle dataset, so I'm not sure we'll be able to support download (but maybe)

Nope. Downloads from Kaggle are currently not supported, since they require login. For now I would simply not add a `download` flag. Later in the new style datasets, we can provide them as 

https://github.com/pytorch/vision/blob/eac3dc7bab436725b0ba65e556d3a6ffd43c24e1/torchvision/prototype/datasets/utils/_resource.py#L168

**Comment by abhi-glitchhg** [comment]
Can I try the Stanford cars dataset?

**Comment by jdsgomes** [comment]
I am taking the Food 101 now now.

**Comment by fibbonnaci** [comment]
I was planning on taking the Stanford Cars dataset. @abhi-glitchhg if you're taking it, then I'll try the Food101 dataset

**Comment by fibbonnaci** [comment]
> I am taking the Food 101 now now.

Dang, I'm a few seconds late. I'll try PCAM then.

**Comment by zhiqwang** [comment]
I was planning on taking the Flowers-102.

**Comment by oke-aditya** [comment]
I am planning to take SUN dataset. 
I'm unsure of my time and bandwidth as I would be working in office from next month.
Any contributor can supersede me :smile:

**Comment by sumukhaithal6** [comment]
I am planning to work on the GSTRB dataset.

**Comment by frgfm** [comment]
Coming late to the party, but I'd be keen to take care of EuroSAT :+1: 
Glad to hear the dataset zoo is extending :smile:

**Comment by pmeier** [comment]
@ everyone who volunteered to take a dataset: thanks a lot! @NicolasHug will be out until next year, so feel free to ping me on PRs.

**Comment by sallysyw** [comment]
I'll take FGVC-Aircraft :)

**Comment by puhuk** [comment]
I'll take Country211 :)

**Comment by saswatpp** [comment]
@oke-aditya Mind if I take the SUN dataset task, please ?

**Comment by oke-aditya** [comment]
Sure.

**Comment by pmeier** [comment]
I would be grateful, ff someone is also up to adding their dataset also for the upcoming new style of the datasets. I've just added #5133 that details how this should be done. So far no one besides the core team has worked on that so we are actively looking for feedback on the contributor experience.

**Comment by frgfm** [comment]
> I would be grateful, if someone is also up to adding their dataset also for the upcoming new style of the datasets. I've just added #5133 that details how this should be done. So far no one besides the core team has worked on that so we are actively looking for feedback on the contributor experience.

Oh nice, I read about those prototypes and was curious to play around with it :grin: 
Just to make sure I understand this: do you mean adding a second implementation of one of those datasets using the prototypes? or do you mean changing already implemented ones to use the prototypes?

**Comment by pmeier** [comment]
> Just to make sure I understand this: do you mean adding a second implementation of one of those datasets using the prototypes? 

Exactly. Let me know if you hit any roadblocks as I'm eager to get feedback.

**Comment by jdsgomes** [comment]
Hello @zhiqwang 👋 
Are you still planning to work on the  Flowers-102? 
If you are no longer interested or don't have time thats obviously ok, but we can put it up for grabs since we are aiming to finish this month.

**Comment by pmeier** [comment]
Same for @fibbonnaci and the PCAM dataset.

**Comment by zhiqwang** [comment]
Hi @jdsgomes , I'm working on this now, and hope to submit the PR today.

**Comment by NicolasHug** [comment]
Thanks a lot of offering to help with the prototypes @frgfm . Let me know which one(s) you're trying to implement so we don't overlap :) . On my side I'll give try to GTSRB.

**Comment by pmeier** [comment]
Hey @fibbonnaci, PCAM is the last dataset that does not have a PR up yet. Are you working on that? If yes please push a PR even if you are not done, so we can help out and accelerate this. Otherwise, I'll send one myself.

**Comment by NicolasHug** [comment]
As discussed with @fibbonnaci offline, I'll take over the PCAM dataset.

**Comment by NicolasHug** [comment]
Looks like we're all done

Thank you so much everyone who submitted a dataset, your help is much appreciated!

Tons of thanks to @pmeier in particular for all your help with submissions and the reviews!!
