### ISSUE TITLE
[RFC] Implement transforms primitives for Bounding Boxes

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#5514]
Related tracker issue: https://github.com/pytorch/vision/issues/5754

## Functional transforms for bboxes

The idea is to implement the following low-level functional transforms for bounding boxes:
https://github.com/pytorch/vision/blob/main/torchvision/prototype/transforms/functional/_geometry.py
- [x] affine_bounding_box (@vfdev-5) #5597
- [x] rotate_bounding_box (@vfdev-5) #5638
- [x] perspective_bounding_box (@vfdev-5) #5888
- [x] center_crop_bounding_box (@vfdev-5) #5972
- [x] crop_bounding_box (@vfdev-5) #5781
- [x] resized_crop_bounding_box (@vfdev-5) #5853
- [x] pad_bounding_box (@pmeier) #5551, #6038
- [x] vertical_flip_bounding_box #5633

## How to test the implementation ?

Put tests into `test/test_prototype_transforms_functional.py`:
- correctness test
- eager vs scripted
- scriptable
- check on cpu and cuda

cc @vfdev-5 @datumbox @bjuncek

**Comment by vfdev-5** [comment]
@pmeier can you provide tests for `pad_bounding_box` such that we could close this tracker ? Thanks

**Comment by pmeier** [comment]
Thanks for reminding me!

**Comment by vfdev-5** [comment]
I'm closing this tracker as done
