### ISSUE TITLE
[RFC] Implement transforms primitives for Segmentation Masks 

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#5782]
Related tracker issue: #5754

## Functional transforms for segmentation masks

The idea is to implement the following low-level functional transforms for segmentation masks:
https://github.com/pytorch/vision/blob/main/torchvision/prototype/transforms/functional/_geometry.py

- [x] affine_segmentation_mask (@vfdev-5) #5613
- [x] rotate_segmentation_mask (@vfdev-5) #5692
- [x] perspective_segmentation_mask (@vfdev-5) #5888
- [x] center_crop_segmentation_mask (@federicopozzi33) #5961
- [x] crop_segmentation_mask (@vfdev-5) #5851
- [x] resized_crop_segmentation_mask (@vfdev-5) #5855
- [x] pad_segmentation_mask (@federicopozzi33) #5866, need more tests: https://github.com/pytorch/vision/pull/5866/files#r859158083 -> https://github.com/pytorch/vision/pull/6104
- [x] vertical_flip_segmentation_mask (@federicopozzi33) #5860, #5633

## How to test the implementation ?

Put tests into `test/test_prototype_transforms_functional.py`:
- correctness test
- eager vs scripted
- scriptable
- check on cpu and cuda

cc @vfdev-5 @datumbox @bjuncek

**Comment by federicopozzi33** [comment]
Hi @vfdev-5,

I would like to work on _vertical_flip_segmentation_mask_ primitive.

**Comment by vfdev-5** [comment]
@federicopozzi33 sure, go ahead!

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/vision/issues/4415

**Comment by federicopozzi33** [comment]
@vfdev-5,

I'd like to go on with _pad_segmentation_mask_ primitive.

**Comment by vfdev-5** [comment]
Thanks @federicopozzi33 , sure go ahead !

**Comment by federicopozzi33** [comment]
I'd like to complete this issue doing _center_crop_segmentation_mask_.

**Comment by vfdev-5** [comment]
@pmeier in order to close this tracker as done we have to add more correctness tests for padding with other padding modes (https://github.com/pytorch/vision/pull/5866/files#r859158083)

`pad_segmentation_mask` uses `pad_image_tensor` and right now we does not have any tests for `pad_image_tensor`. I suggest to check correctness with one of suggested ways (from the link above). Later these tests could be reused for checking `pad_image_tensor`.

Any other suggestions from your side ?

**Comment by pmeier** [comment]
Nope, sounds like a good plan.

**Comment by vfdev-5** [comment]
I'm closing this tracker as done
