### ISSUE TITLE
Improve documentation for Multi-weight support

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6014]
### 📚 The doc issue

Previously we have restructured the documentation for models (#5833, #5987, #5897 etc), so that we can add necessary information about how the models were trained and integrate with the new Multi-weight support API.

This ticket is a tracker for all remaining tasks related to model documentation + Multi-weight support API:
- [x] Clean up the documentation pages #6003 #6002
- [x] Include information about the preprocessing transforms of models #6009
- [x] Add examples on how to use the new Multi-weight model builders #6013 
- [x] Move from the old `models.srt` any useful info to the new one (TORCH_HOME + TorchHub info, train/eval modes etc) #6026 #6025
- [x] Update galleries to use new idioms (for example fetching [classes](https://github.com/pytorch/vision/blob/11bd2eaa6d6976129836b329b01d1300babddcc9/gallery/plot_visualization_utils.py#L149) from meta-data and the text concerning [preprocessing](https://github.com/pytorch/vision/blob/11bd2eaa6d6976129836b329b01d1300babddcc9/gallery/plot_visualization_utils.py#L122-L124)) #6030
- [ ] Add description to pre-trained weights that clarify their scope #6036 #6039
